### ISSUE TITLE
Download report bug with `domain` route

### ISSUE THREAD

**Issue by tdlowden** [18F/analytics-reporter-api#12]
As per @lauraGgit, the way the <domain> route works for the download report is that is take the initial 1000 default limit and culls the domain data from that. So, for example, using `/domain/epa.gov/report/download` returns about 30 results, because there were 30 relevant datapoints from the initial 1000 limit.

Is there a way we can make this more consistent?

**Comment by levinmr** [comment]
Fixed by changing the implementation to do the filtering at the query level
